package br.com.nicoletti.busapi.utils;

public interface BusExceptions {

	// Erros serviço rest
	String REST_SERVICE_RESPONSE_CODE_IS_NOT_OK = "REST-0001";
	String REST_SERVICE_ERROR_TEMPLATE_CLIENT = "REST-0002";
	String REST_SERVICE_UNKNOW_ERROR = "REST-0003";

	// Erros serviço de loteria
	String LOTTERY_SERVICE_ERROR_ONLINE_RESULT_RETURNED_ERROR = "LOT-0001";
	String LOTTERY_SERVICE_ERROR_PARSE_JSON = "LOT-0002";
	String LOTTERY_SERVICE_UNKNOW_ERROR = "LOT-0003";
	String LOTTERY_SERVICE_GAME_TYPE_NOT_FOUND = "LOT-0004";
	String LOTTERY_SERVICE_ERROR_PARSE_DATE = "LOT-0005";
	String LOTTERY_SERVICE_TYPE_GAME_IS_UNDEFINED = "LOT-0006";
	String LOTTERY_SERVICE_ERROR_GAME_NOT_FOUND = "LOT-0007";

	// Erros no serviço de previsão do tempo
	String FORECAST_SERVICE_CITY_NOT_FOUND = "FORE-0001";
	String FORECAST_SERVICE_MISSING_PARAMETER_CITY_NAME = "FORE-0002";
	String FORECAST_SERVICE_MISSING_PARAMETER_CITY_ID = "FORE-0003";
	String FORECAST_SERVICE_UNKNOW_ERROR = "REST-0004";

}
